image: python:3.12

stages:
  - update_readme
  - commit_and_push

update_readme:
  stage: update_readme
  script:
    python generate_solution_tables.py
  only:
    - main

commit_and_push:
  stage: commit_and_push
  script:
    - git add README.md
    - git commit -m "Update README.md"
    - git push